site_name: Pandunia
site_url: http://www.pandunia.info/fransi
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../fransi
site_dir: ../../html/fransi
theme: readthedocs
plugins:
    - search:
        lang: fr
nav:
    - Accueil: 'index.md'
    - 'Info':
        - 'Présentation': dunia_baxe.md
        - 'Principes de fonctionnement': filsofe.md
        - 'Questions et réponses': eske_i_jawabe.md
        - 'Traduire ce site': tarja_netoloke.md
    - 'Grammaire':
        - 100_bazi_kanune.md
        - 101_dunia_loge.md
        - 102_ABC.md
        - 104_namloge.md
        - 105_sifloge.md
        - 106_modologe.md
        - 107_numloge.md
        - 108_visloge.md
        - 109_karloge.md
        - 110_jumle.md
        - 111_logobine.md
    - 'Leçons':
        - 'Écriture et prononciation': abc.md
        - 'Phrases courantes': fraze.md
        - 'Leçons': darse.md
    - 'Vocabulaire':
        - 'Pandunia → français': pandunia-fransi.md
        - 'Français → pandunia': fransi-pandunia.md
        - 'Etymologie': leksaslia.md
    - 'Grammaire': kanun.md

