site_name: язык пандуния
site_url: http://www.pandunia.info/rus
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../rus
site_dir: ../../html/rus
use_directory_urls: false
theme:
  name: material
  language: ru
  logo: logo.png
  favicon: favicon.png
  palette:
    primary: blue
  font:
    code: Ubuntu mono
plugins:
    - search:
        lang: ru
nav:
    - Дом: 'index.md'
    - 'Звучание': G-ABC.md
    - G-PoS.md
    - G-PRO.md
    - G-N.md
    - G-NUM.md
    - G-P.md
    - G-AFX.md
    - 'Уроки': K-kurse.md
    - 'Словарь':
        - 'пандуния-русский': pandunia-rus.md
        - 'русский-пандуния': rus-pandunia.md
        - 'этимология': lexaslia.md
extra:
  alternate:
    - name: English
      link: https://pandunia.info/eng/
      lang: en
    - name: Español
      link: https://pandunia.info/spa/
      lang: es
    - name: Esperanto
      link: https://pandunia.info/epo/
      lang: eo
    - name: Français
      link: https://pandunia.info/fra/
      lang: fr
    - name: Italiano
      link: https://pandunia.info/ita/
      lang: it
    - name: Polski
      link: https://pandunia.info/pol/
      lang: pl
    - name: Português
      link: https://pandunia.info/por/
      lang: pt
    - name: Melayu
      link: https://pandunia.info/may/
      lang: id
    - name: Suomi
      link: https://pandunia.info/fin/
      lang: fi
    - name: Русский
      link: https://pandunia.info/rus/
      lang: ru
    - name: 日本語
      link: https://pandunia.info/jpn/
      lang: jp
    - name: 中文
      link: https://pandunia.info/zho/
      lang: zh
    - name: ภาษาไทย
      link: https://pandunia.info/tha/
      lang: th
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
