site_name: lingvo Pandunia
site_url: http://www.pandunia.info/epo
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../epo
site_dir: ../../html/epo
use_directory_urls: false
theme:
  name: material
  language: eo
  logo: logo.png
  favicon: favicon.png
  palette:
    primary: blue
extra_css:
  - stile.css
nav:
    - 'Ĉefpaĝo': 'index.md'
    - 'Strukturo de Pandunia':
        - 'Bazaj reguloj': G-baze.md
        - 'Tutmonda vortaro': L-lexe.md
        - 'Prononco': G-ABC.md
        - 'Pronomoj': G-PRO.md
        - 'Substantivoj': G-N.md
        - 'Nombrovortoj': G-NUM.md
        - 'Modifaj vortoj': G-ADJ.md
        - 'Verboj': G-V.md
        - 'Vortfarado': G-AFX.md
    - 'Lecionoj':
        - 'Utilaj frazoj': K-fraze.md
    - 'Vortaroj':
        - 'Pandunia-Esperanto': pandunia-epo.md
        - 'Esperanto-Pandunia': epo-pandunia.md
        - 'Etimologia vortaro': lexaslia.md
extra:
  alternate:
    - name: English
      link: https://pandunia.info/eng/
      lang: en
    - name: Español
      link: https://pandunia.info/spa/
      lang: es
    - name: Esperanto
      link: https://pandunia.info/epo/
      lang: eo
    - name: Français
      link: https://pandunia.info/fra/
      lang: fr
    - name: Italiano
      link: https://pandunia.info/ita/
      lang: it
    - name: Polski
      link: https://pandunia.info/pol/
      lang: pl
    - name: Português
      link: https://pandunia.info/por/
      lang: pt
    - name: Melayu
      link: https://pandunia.info/may/
      lang: id
    - name: Suomi
      link: https://pandunia.info/fin/
      lang: fi
    - name: Русский
      link: https://pandunia.info/rus/
      lang: ru
    - name: 日本語
      link: https://pandunia.info/jpn/
      lang: jp
    - name: 中文
      link: https://pandunia.info/zho/
      lang: zh
    - name: ภาษาไทย
      link: https://pandunia.info/tha/
      lang: th
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://pandunia.telegramo.org/
markdown_extensions:
  - toc:
      toc_depth: 2

