site_name: Pandunia
site_url: http://www.pandunia.info/esperanti
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../esperanti
site_dir: ../../html/esperanti
theme: cerulean
nav:
    - 'Ĉefpaĝo': 'index.md'
    - 'Info':
        - 'Enkonduko': dunia_baxe.md
    - 'Lecionoj':
        - 'Prononco': abc.md
        - 'Utilaj frazoj': fraze.md
    - 'Vortaroj':
        - 'Internaciaj vortaroj': loga.md
        - 'Pandunia-Esperanto': pandunia-esperanti.md
        - 'Esperanto-Pandunia': esperanti-pandunia.md
        - 'Etimologia vortaro': leksaslia.md
    - 'Gramatiko': kanun.md

