site_name: język Pandunia
site_url: http://www.pandunia.info/pol
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../pol
site_dir: ../../html/pol
use_directory_urls: false
theme:
  name: material
  language: pl
  logo: logo.png
  favicon: favicon.png
extra_css:
  - stile.css
nav:
    - Główna: 'index.md'
    - 'Info':
        - 'Wprowadzenie': I-idea.md
        - 'Założenia': I-filosofia.md
    - 'Gramatyka':
        - G-baze.md
        - 'Dźwięki i litery': G-ABC.md
        - G-PRO.md
        - G-N.md
        - G-NUM.md
        - G-ADJ.md
        - G-P.md
        - G-AFX.md
    - 'Nauka':
        - 'Rozmówki': K-fraze.md
        - 'Kurs': K-kurse.md
    - 'Słownik':
        - 'Pandunia-polski': pandunia-pol.md
        - 'Polski-pandunia': pol-pandunia.md
        - 'Etymologia': leksaslia.md
        - 'Wyszukaj': https://www.pandunia.info/lexia/?d=pol
extra:
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
