site_name: Pandunia
site_url: http://www.pandunia.info/engli
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../engli
site_dir: ../../html/engli
theme: readthedocs
nav:
    - Home: 'index.md'
    - 'Info':
        - 'Introduction': dunia_baxe.md
        - 'Principles': filsof.md
        - 'Questions & Answers': eske_i_jawabe.md
        - 'Translate this site': tarja_netoloke.md
    - 'Grammar and Rules':
        - 'The basic rules': 100_bazi_kanune.md
        - 'World words': 101_duni_lekse.md
        - 'Spelling and pronunciation': 102_ABC.md
        - 'Nouns': 104_namloge.md
        - 'Adjectives': 105_sifloge.md
        - 'Adverbs': 106_modologe.md
        - 'Numerals': 107_nume.md
        - 'Pronouns': 108_visloge.md
        - 'Verbs': 109_karloge.md
        - 'Sentences': 110_jumle.md
        - 'Word building': 111_logobine.md
    - 'Lessons':
        - 'Basic Phrases': fraze.md
        - 'Course': darse.md
    - 'Words':
        - 'Pandunia-English': pandunia-engli.md
        - 'English-Pandunia': engli-pandunia.md
        - 'Origins of words': leksaslia.md
        - 'Search': tiddly.html

