site_name: Pandunia language
site_url: https://www.pandunia.info
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../eng
site_dir: ../../html/eng
use_directory_urls: false
theme:
  name: material
  logo: logo.png
  favicon: favicon.png
  palette:
    primary: blue
extra_css:
  - stile.css
nav:
    - 'Introduction': I-idea.md
    - 'Grammar and Rules':
        - 'The basic rules': G-baze.md
        - 'World words': L-lexe.md
        - 'Spelling and pronunciation': G-ABC.md
        - 'Word classes': G-PoS.md
        - 'Pronouns': G-PRO.md
        - 'Nouns': G-N.md
        - 'Numerals': G-NUM.md
        - 'Adjectives': G-ADJ.md
        - 'Adverbs': G-ADV.md
        - 'Verbs': G-V.md
        - 'Prepositions': G-PP.md
        - 'Sentences': G-P.md
        - 'Word building': G-AFX.md
    - 'Lessons':
        - 'Basic Phrases': K-fraze.md
        - 'Course': K-kurse.md
    - 'Words':
        - 'Pandunia-English': pandunia-eng.md
        - 'English-Pandunia': eng-pandunia.md
        - 'Origins of words': lexaslia.md
        - 'Search': https://www.pandunia.info/lexia/?d=eng
    - 'Videos': I-filme.md
    - 'Info':
        - History: I-historia.md
        - 'Questions & Answers': FAQ.md
        - 'Esperanto vs. Pandunia': I-esperanto_vs_pandunia.md
        - 'Adapting foreign words' : L02_lexe_modifikation.md
        - 'Translate this site': M01_trabashe.md
extra:
  alternate:
    - name: English
      link: https://pandunia.info/eng/
      lang: en
    - name: Español
      link: https://pandunia.info/spa/
      lang: es
    - name: Esperanto
      link: https://pandunia.info/epo/
      lang: eo
    - name: Français
      link: https://pandunia.info/fra/
      lang: fr
    - name: Italiano
      link: https://pandunia.info/ita/
      lang: it
    - name: Polski
      link: https://pandunia.info/pol/
      lang: pl
    - name: Português
      link: https://pandunia.info/por/
      lang: pt
    - name: Melayu
      link: https://pandunia.info/may/
      lang: id
    - name: Suomi
      link: https://pandunia.info/fin/
      lang: fi
    - name: Русский
      link: https://pandunia.info/rus/
      lang: ru
    - name: 日本語
      link: https://pandunia.info/jpn/
      lang: jp
    - name: 中文
      link: https://pandunia.info/zho/
      lang: zh
    - name: ภาษาไทย
      link: https://pandunia.info/tha/
      lang: th
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
