site_name: Pandunia
site_url: http://www.pandunia.info/suomi
repo_url: https://github.com/barumau/pandunia/
site_author: Risto Kupsala
docs_dir: ../../suomi
site_dir: ../../html/suomi
theme:
  name: cerulean
  language: fi
plugins:
    - search:
        lang: fi
nav:
    - Kotisivu: 'index.md'
    - 'Tietoa':
        - 'Maailman yhteyskieli': dunia_baxe.md
        - 'Kysymyksiä & vastauksia': eske_i_jawabe.md
    - 'Opiskelu':
        - 'Ääntäminen': abc.md
        - 'Lauseita': fraze.md
        - 'Kurssi': darse.md
    - 'Sanasto':
        - 'Maailman sanastot': dunia_loge.md
        - 'Pandunia-suomi': pandunia-suomi.md
        - 'Suomi-pandunia': suomi-pandunia.md
        - 'Alkuperäsanasto': leksaslia.md
    - 'Kielioppi': kanun.md

