site_name: langue Pandunia
site_url: http://www.pandunia.info/fra
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../fra
site_dir: ../../html/fra
use_directory_urls: false
theme:
  name: material
  language: fr
  logo: logo.png
  favicon: favicon.png
  palette:
    primary: blue
extra_css:
  - stile.css
plugins:
    - search:
        lang: fr
nav:
    - Accueil: 'index.md'
    - 'Présentation': I-idea.md
    - 'Grammaire':
        - G-baze.md
        - L-lexe.md
        - G-ABC.md
        - G-PRO.md
        - G-N.md
        - G-NUM.md
        - G-ADJ.md
        - G-V.md
        - G-P.md
        - G-AFX.md
    - 'Leçons':
        - 'Phrases courantes': K-fraze.md
        - 'Leçons': K-kurse.md
    - 'Vocabulaire':
        - 'Pandunia → français': pandunia-fra.md
        - 'Français → pandunia': fra-pandunia.md
        - 'Etymologie': lexaslia.md
        - 'Recherche': https://www.pandunia.info/lexia/?d=fra
    - 'Appendix':
        - 'Questions et réponses': FAQ.md
        - 'Traduire ce site': tarja_netoloke.md
extra:
  alternate:
    - name: English
      link: https://pandunia.info/eng/
      lang: en
    - name: Español
      link: https://pandunia.info/spa/
      lang: es
    - name: Esperanto
      link: https://pandunia.info/epo/
      lang: eo
    - name: Français
      link: https://pandunia.info/fra/
      lang: fr
    - name: Italiano
      link: https://pandunia.info/ita/
      lang: it
    - name: Polski
      link: https://pandunia.info/pol/
      lang: pl
    - name: Português
      link: https://pandunia.info/por/
      lang: pt
    - name: Melayu
      link: https://pandunia.info/may/
      lang: id
    - name: Suomi
      link: https://pandunia.info/fin/
      lang: fi
    - name: Русский
      link: https://pandunia.info/rus/
      lang: ru
    - name: 日本語
      link: https://pandunia.info/jpn/
      lang: jp
    - name: 中文
      link: https://pandunia.info/zho/
      lang: zh
    - name: ภาษาไทย
      link: https://pandunia.info/tha/
      lang: th
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
