site_name: パンドゥニア
site_url: http://www.pandunia.info/jpn
repo_url: https://github.com/barumau/pandunia/
docs_dir: ../../jpn
site_dir: ../../html/jpn
use_directory_urls: false
theme:
  name: material
  language: ja
  logo: logo.png
  favicon: favicon.png
  palette:
    primary: blue
  font:
    code: Ubuntu mono
nav:
    - '基本': I-suma.md
    - '文法':
        - '基本事項': G-baze.md
        - 'つづり': G-ABC.md
        - '品詞': G-PoS.md
        - '代名詞': G-PRO.md
        - '名詞': G-N.md
        - '数詞': G-NUM.md
        - '修飾詞': G-ADJ.md
        - '副詞': G-ADV.md
        - '動詞': G-V.md
        - '前置詞': G-PP.md
        - '文章': G-P.md
        - '単語の構築': G-AFX.md
    - 'フレーズ集': K-fraze.md
    - '対話形式のレッスン': K-kurse.md
    - '辞典': pandunia-jpn.md
    - 'よくある質問': FAQ.md
extra:
  alternate:
    - name: English
      link: https://pandunia.info/eng/
      lang: en
    - name: Español
      link: https://pandunia.info/spa/
      lang: es
    - name: Esperanto
      link: https://pandunia.info/epo/
      lang: eo
    - name: Français
      link: https://pandunia.info/fra/
      lang: fr
    - name: Italiano
      link: https://pandunia.info/ita/
      lang: it
    - name: Polski
      link: https://pandunia.info/pol/
      lang: pl
    - name: Português
      link: https://pandunia.info/por/
      lang: pt
    - name: Melayu
      link: https://pandunia.info/may/
      lang: id
    - name: Suomi
      link: https://pandunia.info/fin/
      lang: fi
    - name: Русский
      link: https://pandunia.info/rus/
      lang: ru
    - name: 日本語
      link: https://pandunia.info/jpn/
      lang: jp
    - name: 中文
      link: https://pandunia.info/zho/
      lang: zh
    - name: ภาษาไทย
      link: https://pandunia.info/tha/
      lang: th
  social:
    - icon: fontawesome/regular/comments
      link: https://pandunia.info/forum/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/pandunia/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jf5GHcHXKk
    - icon: fontawesome/brands/facebook
      link: http://www.facebook.com/groups/pandunia
    - icon: fontawesome/brands/telegram
      link: https://t.me/pandunia_grupe
markdown_extensions:
  - toc:
      toc_depth: 2
